# Generated by Django 4.1.4 on 2022-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='cny',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
