# Generated by Django 4.1.4 on 2022-12-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archives_cny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='eur',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='archives',
            name='usd',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
