# Generated by Django 4.1.4 on 2022-12-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_alter_archives_eur_alter_archives_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archives',
            old_name='cny',
            new_name='rur',
        ),
    ]
