# Generated by Django 4.1.4 on 2022-12-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_rename_cny_archives_rur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archives',
            old_name='rur',
            new_name='rub',
        ),
    ]
