# Generated by Django 4.1.4 on 2022-12-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_alter_archives_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='user',
        ),
    ]
